FROM node:22-alpine AS builder

WORKDIR /workspace

COPY packages ./packages

RUN npm install -g pnpm

WORKDIR /workspace/packages/database
RUN pnpm install && pnpm run build

WORKDIR /workspace/packages/logger
RUN pnpm install && pnpm run build


WORKDIR /workspace

COPY services/auth-service/package*.json ./services/auth-service/

WORKDIR /workspace/services/auth-service
RUN pnpm install

COPY services/auth-service/package*.json ./
COPY services/auth-service/tsconfig.json ./
COPY services/auth-service/src ./src

RUN pnpm run build

# ------------------------------------------------------------

# Production stage
FROM node:22-alpine

WORKDIR /workspace

# Copy built assets from builder
COPY --from=builder /workspace/packages ./packages
COPY --from=builder /workspace/services/auth-service/dist ./services/auth-service/dist
COPY --from=builder /workspace/services/auth-service/package*.json ./services/auth-service/

WORKDIR /workspace/services/auth-service

ENV NODE_ENV=production

RUN npm install -g pnpm

RUN pnpm i --prod

EXPOSE 7001

CMD ["node", "dist/app.js"]
